source 'https://rubygems.org'

ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :development, :test do
  gem 'rspec-rails', '~> 2.14.0'
end

group :test do
  gem 'capybara', '~> 2.1.0'
  gem 'database_cleaner', '~> 1.0.1'
end

group :doc do
  gem 'sdoc', require: false
end
